# Generated by Django 5.0.3 on 2024-03-18 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pack',
        ),
    ]
