# Generated by Django 5.0.3 on 2024-03-18 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('planes', '0001_initial'),
        ('suscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='suscripcion',
            unique_together={('plan', 'cliente')},
        ),
    ]
